# Generated by Django 5.1 on 2024-08-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrados',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
