# Generated by Django 5.1 on 2024-08-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organx', '0002_cadastrados_data_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
