# Generated by Django 5.1 on 2024-08-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organx', '0003_alter_cadastrados_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrados',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
