# Generated by Django 5.1 on 2024-08-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organx', '0004_alter_cadastrados_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrados',
            name='Função',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrados',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrados',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrados',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrados',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrados',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
